name: Build & Deploy ISKI.SARS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test --configuration Release --no-build

      - name: Publish WebUI
        run: dotnet publish ISKI.SARS.WebUI/ISKI.SARS.WebUI.csproj -c Release -o ./publish /p:PublishIISAssets=true

      - name: Zero-downtime deploy to IIS
        shell: pwsh
        run: |
          $src = (Resolve-Path "./publish").Path
          $dst = "C:\inetpub\wwwroot\ISKI.SARS"
          Set-Content "$dst\app_offline.htm" "Maintenance" -Encoding ASCII
          robocopy $src $dst /MIR /R:2 /W:2
          Remove-Item "$dst\app_offline.htm" -ErrorAction SilentlyContinue
